apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: vmfarms
  labels:
    app.kubernetes.io/name: vmfarms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmfarms
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60