{{- if .Values.ingress.enabled -}}
{{- $env := coalesce .Values.env "other" }}
{{- $name := include "vmfarms.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vmfarms.fullname" . }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  {{- range .Values.domain }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: ssl-redirect
              port:
                name: use-annotation
        - backend:
            service:
              name: vmfarms
              port:
                number: 8080
          path: /
          pathType: Prefix
  {{- end }}
{{- end -}}          